apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whatsapp-intregation.fullname" . }}
  labels:
    {{- include "whatsapp-intregation.labels" . | nindent 4 }}
type: Opaque
data:
  # API_KEY is base64-encoded here (Helm encodes .Values strings with b64enc)
  api-key: {{ .Values.secret.apiKey | b64enc | quote }}
