apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-intregation.fullname" . }}
  labels: {{- include "telegram-intregation.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secret.apiKey | b64enc | quote }}
  bot-token: {{ .Values.secret.botToken | b64enc | quote }}
